### ISSUE TITLE
AMIRIS should consider fuel prices fed from EMLabpy

### ISSUE THREAD

**Issue by IngridJSJ** [TradeRES/toolbox-amiris-emlab#23]
EMLabpy write prices in amiris_data_structure.xlsx and shouhld be written into scenario.yaml

**Comment by dlr-jk** [comment]
I think after today's meeting, we can close this issue and agree on the workaround using the OPEX value to feed all the information.

If you desire to change it, feel free to reopen, @IngridJSJ.
