### ISSUE TITLE
Fix batteries

### ISSUE THREAD

**Issue by IngridJSJ** [TradeRES/toolbox-amiris-emlab#25]
Batteries are not active and might not see the VOLL scarcity levels. 
Also: Export energy level for next year.

**Comment by dlr-jk** [comment]
For the first aspect, we'll dig into that, but it is most likely due to the system constellations considered.
For the latter aspect, you need the final energy level as starting point for the simulation of the following year, right?

**Comment by dlr-jk** [comment]
These are two separate issues. I'll close and open dedicated ones.
